# preload = /home/linnsheng/Downloads/porsche.png
# wallpaper =  /home/linnsheng/Downloads/porsche.png
# preload = /home/linnsheng/Downloads/PalatteWallpapers/5k_11.png
# wallpaper = ,/home/linnsheng/Downloads/PalatteWallpapers/5k_11.png
# fit_mode = cover
# splash = false
# ipc = off
wallpaper {
    monitor =
    path = /home/linnsheng/Downloads/PalatteWallpapers/5k_11.png
    fit_mode = cover
}

splash = false
