# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

#windowrule = match:class ..*, border_size 0

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

windowrule = match:float true, border_size 0

windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus on

# windowrule = match:float true, center on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, size 40% 45%
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, center on

# 3. Center it
windowrule = match:class (.*org.pulseaudio.pavucontrol.*), center on
windowrule = match:class (.*pavucontrol.*), center on
windowrule = match:class ^(nwg-displays)$, float on
windowrule = match:class ^(nwg-displays)$, size 80% 80%
windowrule = match:class ^(nwg-displays)$, center on

windowrule = match:class ^(Nsxiv)$, float on
windowrule = match:class ^(Nsxiv)$, size 80% 80%
windowrule = match:class ^(Nsxiv)$, center on

windowrule = match:class ^(zen)$, opacity 0.95 0.95
